### ISSUE TITLE
The custom keymap not working

### ISSUE THREAD

**Issue by l1Dan** [zed-industries/community#1049]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

custom keymap not working
<img width="888" alt="截屏2023-03-12 08 57 49" src="https://user-images.githubusercontent.com/7961100/224518483-2d625718-d79f-4642-8dd5-5d540f1a5c7b.png">

### Environment

Zed: v0.75.2 (stable)
OS: macOS 12.6.3
Memory: 8 GiB
Architecture: x86_64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by l1Dan** [comment]
Unable to add binding of ProjectPanel shortcut keys to  NewFolder:
```
[
    {
        "context": "ProjectPanel",
        "bindings": {
            "alt-cmd-N": "workspace::NewFolder",
            "cmd-N": "workspace::NewFile"
        }
    }
]
```

**Comment by JosephTLyons** [comment]
Hey @l1Dan,

Give this snippet a shot:

```json
{
  "context": "ProjectPanel",
  "bindings": {
    "cmd-n": "project_panel::AddFile",
    "cmd-shift-n": "project_panel::AddDirectory"
  }
},
```

This is confusing because the project panel's context menu uses `New File` and `New Directory`, but the keymap names for these actions are `project_panel::AddFile` and `project_panel::AddDirectory`.

I went ahead and opened a PR to make these consistent with the names in the context menu: `project_panel::NewFile` and `project_panel::NewDirectory`, but until that lands, the snippet above should work.

**Comment by l1Dan** [comment]
Thank you, it's done😊。
