### ISSUE TITLE
python definition not work for some lib

### ISSUE THREAD

**Issue by locustbaby** [zed-industries/community#1476]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Hello there, 
I wanna to use zed as my python IDE, but I find it can't get the definition with my code.
![image](https://user-images.githubusercontent.com/21237232/234160461-bf1c4506-f823-43d6-918c-82fe07886fd5.png)
But it's work in VScode 
![image](https://user-images.githubusercontent.com/21237232/234160544-a50aa30f-5639-415e-a21d-1391201651d7.png)

And I checked the issues, and used to delete `pyright` with command `rm -rf ~/Library/Application\ Support/Zed/languages/pyright`
But it's still can't work now

Also like this:
![image](https://user-images.githubusercontent.com/21237232/234161522-5a9f9b4b-7a60-4d98-8350-71d1de80c847.png)

But it's work for some lib:
![image](https://user-images.githubusercontent.com/21237232/234161686-5f8f28f9-d8f8-432b-98b5-0c6d287ae8c2.png)

### Environment

Zed 0.82.9
"pyright": "^1.1.304"

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by hovsater** [comment]
Would you mind sharing a minimal reproduction project that I can use for testing purposes?

**Comment by locustbaby** [comment]
> Would you mind sharing a minimal reproduction project that I can use for testing purposes?

```
#!/usr/bin/python3
import configparser
import time
import random
import logging
import datetime
import sys
from pymilvus import connections, utility
from pymilvus import Collection, DataType, FieldSchema, CollectionSchema

logger = logging.getLogger(__name__)

logging.basicConfig(level=logging.DEBUG, format='%(asctime)s %(levelname)-8s %(message)s',
                    datefmt='%a, %d %b %Y %H:%M:%S', filename='testsearch.log', filemode='w')

if __name__ == '__main__':
    # connect to milvus
    cfp = configparser.ConfigParser()
    cfp.read('config.ini')
    milvus_uri = cfp.get('example', 'uri')
    user = cfp.get('example', 'user')
    password = cfp.get('example', 'password')

    connections.connect("default",
                        uri=milvus_uri,
                        user=user,
                        password=password,
                        secure=True)
    print(f"Connecting to DB: {milvus_uri}")
    logging.info(f"Connecting to DB: {milvus_uri}")
```

**Comment by hovsater** [comment]
@locustbaby thanks, but I was more looking for a complete project to clone so I can play around with this on my side. Feel free to create a small repository that is enough to showcase the problems you're seeing. It would also help if you gave a few examples of what you expect to work in the minimal project you've created.

**Comment by locustbaby** [comment]
I'm sorry that maybe it's hard to offer you a runnable code, cause this is an example code to connect a vectorDB(Milvus), which means if you wanna run this code, you need to deploy a Milvus locally.
But the source code is [here](https://raw.githubusercontent.com/milvus-io/pymilvus/v2.2.7/examples/hello_milvus.py)

As to the reproduction, just open the code in Zed and VScode
![image](https://user-images.githubusercontent.com/21237232/234787679-a0045ea4-4991-4beb-b041-19b17a7392a8.png)
![image](https://user-images.githubusercontent.com/21237232/234787821-b94bb983-0934-4f71-a7ea-5c760fc7f1fc.png)

In vscode, we can see the definition of the `Collection`.

In addition, perhaps this issue is not too valuable, can temporarily set aside to wait whether others encounter similar problems, thank you very much for your time

**Comment by Emblaze** [comment]
Hi there.

Running Zed 0.83.2, pyright removed and redownloaded...

FWIW, a simple import pylab yields an "Import "pylab" could not be resolved" error message in Zed, works in VSCodium and actually points to mathplotlib.pyplot.plot when looking at the definition (I'm now aware the use of pylab is no-longer recommanded, but it's included in a fairly recent exercise I'm busy with ATM).

Both Zed and VSCodium are using my system default Python 3.11.3 version (installed via brew).

Hope this helps, please otherwise let me know.

**Comment by hovsater** [comment]
I'm not a Python expert by any means, but I went ahead and did some research. VSCode uses [Pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) which is different from the open-source language server [pyright](https://github.com/microsoft/pyright). Pylance ships with [typings](https://github.com/microsoft/python-type-stubs) for popular libraries, including [matplotlib](https://matplotlib.org) and that's why the experience is better out of the box. There seem to be an effort in making these typings available to pyright as well, even though it's [currently a bit of hassle](https://github.com/microsoft/pylance-release/blob/main/USING_WITH_PYRIGHT.md).

1. I downloaded the Pylance VSCode extension from [here](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance). Replaced the `vsix` extension with `zip` and unzipped it.
2. I then copied `dist/bundled/stubs/matplotlib` from the unzipped contents into `src/stubs` in my test project.
3. I configured pyright like so:
```json
{
  "include": [
    "src"
  ],
  "exclude": [
    "**/node_modules",
    "**/__pycache__",
    "venv"
  ],
  "stubPath": "./src/stubs",
  "venv": "venv",
  "venvPath": "./",
  "reportMissingImports": true,
  "reportMissingTypeStubs": true,
  "pythonVersion": "3.11",
  "pythonPlatform": "Darwin",
  "executionEnvironments": [
    {
      "root": "src"
    }
  ]
}
```
4. And got typings as expected.

<img width="1097" alt="Screenshot 2023-05-02 at 19 38 54" src="https://user-images.githubusercontent.com/503025/235743989-0c73d7d9-5f3a-4e09-8667-8670996d8cf6.png">

**Note:** For testing purposes, I just initialized a new virtual environment within the root of my project using `virtualenv venv`. You most likely don't want to do that, but then again, not a Python expert. 😅

I know this isn't ideal, but it's the same for anyone using an editor outside VScode.
