### ISSUE TITLE
Feature: Select all instances for search (Like Sublime's Find All)

### ISSUE THREAD

**Issue by selfish** [zed-industries/community#1749]
### Check for existing issues

- [X] Completed

### Describe the feature

When searching (buffer), I'd like to be able to define a hotkey for selecting all instances of the search string.

In Sublime, you would <kbd>Cmd</kbd>+<kbd>f</kbd>, type something in, then <kbd>Alt</kbd>+<kbd>Enter</kbd> or (click the "Find All" button) to select all results.

A selection (with a marker at the end of it) would then be placed on every match in the document.

This aligns with the current supported:

Select next match: <kbd>Enter</kbd>
Select prev match: <kbd>Shift</kbd>+<kbd>Enter</kbd>

Suggested:
Select all matches: <kbd>Alt</kbd>+<kbd>Enter</kbd>

Thank you

### If applicable, add mockups / screenshots to help present your vision of the feature

Keymap.json example:

```json
[
  {
    "context": "BufferSearchBar",
    "bindings": {
      "alt+enter": "buffer:search:selectAllMatches"   // ← This is new
    }
  }
]
```

**Comment by SomeoneToIgnore** [comment]
This comes with the 0.96.0 version.

**Comment by SomeoneToIgnore** [comment]
This action is valid in the context of a single buffer search only (since interacts with cmd+g and other related keybindings), and project search is a multibuffer that does not have such search, neither I am aware of any close future plans to add one.

https://github.com/zed-industries/community/issues/75 could help, though: `cmd+d` to select next selection works in project-wide search and any other multibuffer, so whatever enhances it to select every match should work with it too.
Would that functionality help?

**Comment by joeldrapper** [comment]
@SomeoneToIgnore that would definitely help. Alternatively, some kind of find and global find and replace feature would be ideal, especially if the replacement could include regex captures.

**Comment by selfish** [comment]
Sorry for the slow response here; it's great to hear that!
Thank you!
