### ISSUE TITLE
Drag tabs between windows

### ISSUE THREAD

**Issue by rsheidow** [zed-industries/community#1806]
### Check for existing issues

- [X] Completed

### Describe the feature

Similar to most web browsers, the ability to drag a tab from one window to another would be quite beneficial!

**Comment by JosephTLyons** [comment]
Hey @rsheidow ,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/community/issues/493

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.
