### ISSUE TITLE
workspace: restart command should keep unsaved/untitled documents

### ISSUE THREAD

**Issue by futurist** [zed-industries/community#1814]
### Check for existing issues

- [X] Completed

### Describe the feature

as titled, the need is to restart Zed for some reason, but don't want to save unsaved/untitled opening files.

Currently, the restart behavior is just a simple Quit + Start, which will lost all unsaved/untitled opening files.

**Comment by JosephTLyons** [comment]
Hey @futurist ,

I think the following issues cover these requests:

- https://github.com/zed-industries/community/issues/1005
- https://github.com/zed-industries/community/issues/1655

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.
