### ISSUE TITLE
Vim - Change/Delete/Select inside string "..." '...'  not working with Brazilian keyboard

### ISSUE THREAD

**Issue by decomoraes** [zed-industries/community#1913]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Brazilian keyboard to add the character ' and " you have to press the character then press the space, and the zed it's not been able to change, delete and select inside a string.

### Environment

Mac venture 13.4.1, Brazilian keyboard

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by ConradIrwin** [comment]
@decomoraes  The latest Zed preview (v0.104 https://zed.dev/releases/preview) should fix this so that you can remove your new bindings.

I am not used to working on a Brazilian keyboard though, so if you are open to testing it, I would love to know if this works as expected or if it breaks something unexpected.

**Comment by ConradIrwin** [comment]
Closing as fixed now that v0.104 is out to stable.
