### ISSUE TITLE
Drag and drop file to editor to open the file

### ISSUE THREAD

**Issue by ahgood** [zed-industries/community#1916]
### Check for existing issues

- [X] Completed

### Describe the feature

Current, drag and drop a file to Zed and it will do nothing. I think that's a basic function for an editor.

**Comment by JosephTLyons** [comment]
Hey @ahgood,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/community/issues/1317

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.
