### ISSUE TITLE
Hashicorp HCL and Terraform support

### ISSUE THREAD

**Issue by Stallon-niranjan** [zed-industries/community#1928]
### Check for existing issues

- [X] Completed

### Language

hashicorp  hcl

### Tree Sitter parser link

https://github.com/MichaHoffmann/tree-sitter-hcl.git

### Language server link

https://github.com/hashicorp/hcl-lang.git,https://github.com/juliosueiras/terraform-lsp.git

### Misc notes

https://github.com/hashicorp/hcl-lang.git
https://github.com/juliosueiras/terraform-lsp.git

**Comment by JosephTLyons** [comment]
Hey @Stallon-niranjan,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/community/issues/747

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.
