### ISSUE TITLE
Drag'n'drop files

### ISSUE THREAD

**Issue by krstp** [zed-industries/community#1992]
### Check for existing issues

- [X] Completed

### Describe the feature

Allow any file to be dragged and dropped into current work window

**Comment by JosephTLyons** [comment]
Hey @krstp ,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/community/issues/1317

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.

**Comment by krstp** [comment]
I knew it, it was somewhere there. Thanks!
