### ISSUE TITLE
vim mode: "change to Nth character [m]" with `Nct[m]`

### ISSUE THREAD

**Issue by chadoh** [zed-industries/community#2039]
### Check for existing issues

- [X] Completed

### Describe the feature

Multiple related vim mode sequences I'd love to see:

- `3ct,` – delete everything up to the third comma, not including the third comma, and switch to insert mode (change to third comma, not including that comma)
- `3cf,` – change to third comma, _including_ that comma
- `3cE` – change to end of third capital-W Word
- `3ce` – change to end of third lowercase-w word
- `3cB` – delete previous three Words, change to insert mode
- `3cT,` – delete until-but-not-including previous 3 commas, switch to insert
- `3cF,` – delet until previous 3 commas inclusive, switch to insert

This all of course needs to work with the `.` repetition command, as well.

**Comment by ConradIrwin** [comment]
@chadoh Thanks for reporting this!

I coincidentally just fixed these in Zed Preview (https://zed.dev/preview-releases) v0.104.0 (and added the `.` command too!).

Unfortunately (fixing a different issue) I broke keyboard shortcuts that have multiple keys where the second keystroke needs a shift key (which will be fixed in the next release).

If you want to try out v0.104.2 and let me know if `3ct,` etc. and `.` work fine (knowing that `T`, `B`, `F` will be broken) I'd love earlier feedback; that said if you want to wait until the next release goes out I totally understand!

**Comment by ConradIrwin** [comment]
v0.104 is now out, so closing as fixed! Please let me know if you run into anything else
