### ISSUE TITLE
Allow splits to be resized

### ISSUE THREAD

**Issue by iamnbutler** [zed-industries/community#216]
Horizontal splits should have resizable widths, and vertical splits resizable heights. 

This will be really useful with terminal support coming soon (I'll likely always have splits open going forward once this is supported.)

**Comment by JosephTLyons** [comment]
I mentioned this in the other issue in the private repo, but being able to snap splits back to being evenly divided, with a double click, is a nice feature to have, once resizing is available.

**Comment by ricardopieper** [comment]
Now that the terminal is out, this would be great. I created a new modal tab, splitted down, and closed the first one. But dedicating 50% of screen real estate for the terminal is a bit too much.

**Comment by doneill** [comment]
Yes hopefully resizing tabs is on the roadmap.  As far as the terminal, while resizing would help and is the reason I was looking to create an enhancement about pane resizing, I feel like a dedicated bottom view would be a better place for the terminal and possibly other future view tools, e.g. git log, db, debug, etc.

**Comment by AlexW00** [comment]
This is the main issue, that keeps me from using Zed more often. Not being able to resize panes is just hurts.

**Comment by flavormingo** [comment]
I can't wait until this is added. I'm with you, @AlexW00 - I would make Zed my go-to editor even in its early stages right now if it weren't for this missing feature.

**Comment by owen-duncan-snobel** [comment]
I just got into the private alpha for Zed and this is also a deal breaker for me to continue using it seriously

**Comment by petros** [comment]
If it's mostly for the terminal, perhaps using [the dock](https://github.com/zed-industries/community/discussions/943) could help a little bit?

**Comment by WeetHet** [comment]
This is open for half a year now, and I suppose no work is being done, because for me, it looks like it should be easy to make, especially having implemented Dock already. That being said, why is it still open?

**Comment by Kethku** [comment]
It isn't as easy as you'd expect. We use a tree of flex rows and columns to lay out panes today. It's not obvious how that should interact with resizable panes in a way that preserves the benefits you get from automatic layout of tabs.

This is still a high priority for me personally and is something we have discussed off and on over the last 6 months and even before this issue was created.

To put my mod hat on, this issue will get prioritized but saying it should be closed because clearly nothing is happening is not acceptable under the code of conduct. We would have closed it if we decided we weren't going to address it.

**Comment by JosephTLyons** [comment]
> This is open for half a year now, and I suppose no work is being done, because for me, it looks like it should be easy to make, especially having implemented Dock already. That being said, why is it still open?

There and hundreds of features everyone wants, each having users expressing how much they want it as badly as you do.  We're a small team and this product is still in private alpha, we'll 

Just a reminder - we are a small team (< 10) and this product is still in private alpha.  We recognize that this is a popular issue, but the implication behind signing up for a product in private alpha is that the product may not be developed enough to perfectly pleases everyone - quite the opposite, there is almost a guarantee that it will be missing things.

We have hundreds of feature requests, each one having passionate users expressing how badly they want it.  As Kay said, we're not closing it because it's a feature we intend to add, but it will happen when we can find time to slide it in.  It's simply not done because there are technical challenges associated with it.

**Comment by trevyn** [comment]
If you open source, the community can help you add it.

Just a note to the *employees*.

**Comment by mikayla-maki** [comment]
This should be released by v0.97 :)
