### ISSUE TITLE
Assistant not working

### ISSUE THREAD

**Issue by regnarock** [zed-industries/community#2210]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Added my OpenAPI key (and triple checked that I had enough money on the account), and any try to use the assistant results in
```
Failed to parse header value
```

### Environment

Zed: v0.110.2 (stable)
OS: macOS 13.5.2
Memory: 16 GiB
Architecture: x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

<img width="645" alt="Screenshot 2023-11-02 at 5 39 50 PM" src="https://github.com/zed-industries/community/assets/4267223/1183863c-dc32-462c-906b-ff5761fb4ebb">

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

[test.txt](https://github.com/zed-industries/community/files/13242392/test.txt)

**Comment by KCaverly** [comment]
Thanks @regnarock, for the detailed breakdown, can you confirm for me if you are authenticating using an OPENAI_API_KEY environment variable, or your keychain?

**Comment by krstp** [comment]
I would say probably the issue is you do not have valid paid GPT subscription. Change model to GPT-3.5-turbo by clicking the `gpt-4`. I would rather say, it would be nice to specify - say in config file - the GPT model version, instead of it always opening at version 4.

If 3.5 doesn't work either, I would follow @KCaverly advise, make sure you have `OPENAI_API_KEY` env var is defined.

**Comment by regnarock** [comment]
Although I already had `OPENAI_API_KEY` setup in my env. I might not have had restarted zed to allow it to access it.
That's now done and everything works fine !
Thanks a lot for the help 🙇
