### ISSUE TITLE
TypeScript LSP slow

### ISSUE THREAD

**Issue by rista404** [zed-industries/community#2288]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

After some time spent in any TS project the language server has a noticeable delay when doing anything: offering autocomplete, offering imports, marking variables/functions as undefined/defined/used — basically anything. Sometimes it would even mark jsx elements as not found, for example `<span>`.

As for the size of the projects I normally work in, it's not more than ~100-200 tsx files. Mostly Remix apps.

To compare, I sometimes open VSCode when these issues occur and LS seems to work fine. I'm running Zed on a macbook pro 14" M2 Pro.

Sorry to not have more info! I still very much enjoy working in Zed. :v:

### Environment

Zed: v0.113.0 (preview)
OS: macOS 14.1.1
Memory: 16 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

I'll try to take a screen recording next time!

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by kwando** [comment]
Can you check the LSP logs when it is slow/not working? Also would be interesting to see your CPU/RAM usage when it happens.. I can see the same things on my machine.

To see the language server logs
CMD+P "debug: open language server logs"


https://github.com/zed-industries/community/issues/2265
https://github.com/zed-industries/community/issues/2256

**Comment by imevro** [comment]
yeah, same – always feels laggy + i suppose i have memory leak, because after day of coding i'm ending with 3 GB+ memory

<img width="1215" alt="Screenshot 2023-11-22 at 12 29 39" src="https://github.com/zed-industries/community/assets/775692/9b2d1c78-e8a0-4653-b2c0-4aa69e4910ac">

* ~3-4 not big projects, basically next.js with maybe under 100 files total in not .gitignore
* zed version 0.112.3, but it continues on last versions, trying to update, but nothing changes
* will provide logs later today, restarted

**Comment by kwando** [comment]
Looks like you are hitting this https://github.com/zed-industries/community/issues/2265 as well. 

I was just curious.

**Comment by maxbrunsfeld** [comment]
I think this is fixed in the latest version of Zed. Let me know if you're still seeing this after upgrading to Zed 0.114.0 preview (or 0.113.0 stable).
