### ISSUE TITLE
Asciidoc/Asciidoctor support

### ISSUE THREAD

**Issue by buelbr** [zed-industries/community#2336]
### Check for existing issues

- [X] Completed

### Describe the feature

It would be great to have Asciidoc among the languages recognized by Zed.

**Comment by JosephTLyons** [comment]
Hey @buelbr,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/community/issues/1541

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.
