### ISSUE TITLE
The `assistant: { button: false }` setting is no longer honored

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/community#2370]
### Check for existing issues

- [X] Completed

### Describe the feature that was lost

Title

**Comment by tinylucid** [comment]
Just noticed this. Also It would be essential to be able to completely disable any assistant usage. So for example:
`  "assistant": {
    "enabled": false,
  },`
So it removes all UI elements and functionality of AI assistants. As long as it is optional i don't mind it. But I just don't want any AI service accessing and reading my code, nor do I see usage in using AI assistant in what I do.

Handling this functionality would decide whether or not I end up using this otherwise awesome piece of software. :)

**Comment by maxdeviant** [comment]
Whoops, didn't mean to close this yet.

But it is fixed in the next release.

**Comment by maxdeviant** [comment]
This is fixed in v0.119.3.
