### ISSUE TITLE
vim-mode switch/move panes using C-w {h,j,k,l}

### ISSUE THREAD

**Issue by HanEmile** [zed-industries/community#278]
**Before you begin**
Check the backlog of issues to reduce the chances of creating duplicates; if an issue already exists, place a `+1` (👍) on it.

**Is your feature request related to a problem? Please describe.**
Switching and moving panes in vim mode using the keyboard only.

**Describe the solution you'd like**
So in vim, you can normally switch panes by pressing C-w ("Control + w") and then h, j, k or l to move to that pane. Another thing that is kind of tied to that is moving the panes them selves using C-w + H, J, K or L (so the uppercase versions of the previously described action, swaps out the current pane with the pane you'd move to).

**Describe alternatives you've considered**
Well, you could use the mouse, but if you're already using vim mode, why not use the existing vim motions.  

**Screenshots**
Not applicable

**Comment by ConradIrwin** [comment]
@HanEmile The lower-case version of this is now implemented! We haven't built the ability to swap (yet) though.

**Comment by izuzak** [comment]
> The lower-case version of this is now implemented! We haven't built the ability to swap (yet) though.

@ConradIrwin Oh neat, I was just looking for this! ✨ 

Do you perhaps know if this is using a Zed command that can be used even when not in vim mode? I'd find it useful to use such a command even outside of vim mode, via a keyboard shortcut. Since there are already other commands related to panes (e.g. splitting a pane), it doesn't seem unreasonable to have a command for switching panes as well. 🙏 😄

**Comment by ConradIrwin** [comment]
There is not yet, but there should be!

**Comment by ConradIrwin** [comment]
Thanks for your patience here! 

This is implemented in Zed 0.106 (currently in preview, and likely to hit stable next wednesday).

In vim mode, `ctrl-w shift-{h,j,k,l,left,right,up,down}`, and outside of vim mode as `cmd-k shift-{left, right,up,down}`.

**Comment by adri1wald** [comment]
I'm running 0.108.2, but when I do `cmd-k shift-right` nothing happens

**Comment by ConradIrwin** [comment]
@adri1wald that's strange, it should work if you have two (or more) vertical split panes (which you can create with `:vsplit` in vim mode).

We've occasionally seen problems with keyboard shortcuts on non-US keyboards. What layout are you using and I'll try and test it.

Otherwise, is it possible you have a conflicting keybinding configured?
