### ISSUE TITLE
vim-mode commands

### ISSUE THREAD

**Issue by HanEmile** [zed-industries/community#279]
**Before you begin**
Check the backlog of issues to reduce the chances of creating duplicates; if an issue already exists, place a `+1` (👍) on it.

**Is your feature request related to a problem? Please describe.**
my muscle memory kicked in and resulted in me being confused

**Describe the solution you'd like**
So in vim, entering a colon ":" allows to enter a command, such as ":w" saving the current buffer. This currently doesn't happen which is kind of confusing, as when entering ":w", I'd expect that a pane pops up and let's me enter some command or so.

**Describe alternatives you've considered**
I thought of dropping everything in normal mode entered after a colon, until enter is pressed, although that might be even more confusing. Maybe some of you have an Idea on how to handle this in a more vim like fashion?

**Screenshots**
Not applicable

**Comment by lucastrvsn** [comment]
In the future I think would be great to allow us (plugin authors) to hook into command palette and other places of the Zed UI. I think would be great to have the commands: `:vsp` `:sp` `/<search>` `:%s/<find>/<replace>` etc, and also the extremelly powerful `q` to record macros.

In VSCode we have a plugin called [VSCodeVim](https://marketplace.visualstudio.com/items?itemName=vscodevim.vim) that allow us to use the statusbar at the bottom to simulate the actual vim command line, which is so nice and screen space efficient. I don't think these kind of stuff is something Zed should have out-of-the-box but I think is good to allow us to extend those functions using some sort of plugin system (I don't know if Zed has the intention of allowing plugin development).

My dream editor will allow me to do some features of neovim itself (but Zed is almost my dream at the moment):

- Allow me to create floating windows at my glance (to use it to show additional information, completions menus for statusbar, etc, almost like Atom is, e.g. [status-bar](https://github.com/atom/status-bar) and [tree-view](https://github.com/atom/tree-view))
- Allow me to put text in the "virtual text" section of lines
- Allow me to put icons/colors in gutter lines in the line numbers
- Allow me to create keymaps at runtime like [Atom](https://flight-manual.atom.io/behind-atom/sections/keymaps-in-depth/#commands)
- Allow me to use vim-mode in ALL text fields in the editor and control the interface using just vim-like keystrokes

Everything else Zed already has and I see a bright future for this editor. Thank you for all the work Zed team! ❤️

**Comment by dustypomerleau** [comment]
Vim emulation is a massive project, and can be a bit of a thankless task—power Vim users will quickly find every feature you haven't implemented, and both sides end up frustrated.

The model that changed everything for me was the one used by [VSCode Neovim](https://github.com/vscode-neovim/vscode-neovim). Unlike VSCode Vim, VSCode Neovim passes the buffer off to a running instance of Neovim (rather than attempting emulation). I'm able to load `init.vim`, use all my Vim plugins (Easymotion, Surround), and still take advantage of VS Code's features. The experience is remarkably good, and allows both the IDE devs and the plugin dev to offload most of the work to Neovim itself, focusing only on the integration, rather than emulation. I jumped at the chance to sponsor the project, and I think there would be interest in supporting a Zed plugin with the same goals.

**Comment by ramtinabadi** [comment]
Vim commands are necessary. I personally prefer to use Vim motions in a performant IDE with a good ecosystem than terminal. But one of the main reasons of using Vim is to be able to use the same set of commands and key bindings in all platforms and environments. If I need to modify a file in via terminal, I can open up Vim and use my existing muscle memory and knowledge to get things done quickly.

Getting used to the native Zed commands (`cmd+s`) defeats the purpose of being platform-agnostic.

I agree with @dustypomerleau as Vim emulation is extremely massive and probably not the best use of resources. A better approach would be to find a way to embed Neovim, let it handle most of the work and focus more on the integration.

In my opinion, a solid and performant implementation of Vim (better than VSC) can bring a lot of users to Zed. [NVChad](https://github.com/NvChad/NvChad) is a great testament that many people don't want to build up their own rc from the scratch and would prefer a good setup with a good ecosystem. Zed can be the alternative to the terminal to those who want to use Vim motions and commands but not the customization.

**Comment by ConradIrwin** [comment]
A first version of this shipped in Zed v0.106 preview! I've put some documentation here: https://docs.zed.dev/general/vim. Please download the [preview](https://zed.dev/releases/preview) release, try it out, and let me know what is missing for your workflow using the editor's built in feedback or opening new issues for specific commands.

**Comment by izuzak** [comment]
Oh wow, this is aaaaamazing, @ConradIrwin! 😍 Thanks so much for adding this -- the `:%s//` one was something I really missed. 

From the docs:

> Most importantly, regular expressions use the [rust regex crate](https://docs.rs/regex/latest/regex/#syntax) not vim's custom engine, so the syntax differs slightly.

Would it be possible to add a few examples to highlight key differences? Definitely not urgent, but it would make it much easier for folks since they wouldn't need to read the crate's docs and compare every bit to vim's docs. 

Thanks again for this useful feature! ⚡
