### ISSUE TITLE
Ability to move project panel to the right-hand side

### ISSUE THREAD

**Issue by maraisr** [zed-industries/community#287]
Would be nice for the sidebar to be placed on the right hand side of the viewport. Seeing as its toggle-able, be nice for my code pane to not shift right, but rather when toggling to just reduce the space.

Ive uploaded a video of VSCode demonstrating this. Notice how the code stays in tack so i don't loose place mentally, when looking at the pane for example. This would possible be the same for all panes.

https://user-images.githubusercontent.com/599459/178389145-16fea24d-0378-4941-80c6-cc0f6512caa2.mov

**Comment by aexvir** [comment]
yes please! since I've moved the sidebar to the right I've found myself much more focused when coding
I was thinking of opening this issue as well but then I thought that this might worth a longer discussion about the panelling system and not just one sidebar and how that will be used by future features or plugins

it's true that zed currently only has two panels but it will have to get more at some point, and having a flexible and robust system for managing those panels will be the main factor determining how nice to use the editor will be

this is one of the main things vscode has nailed imo

**Comment by sayantank** [comment]
Is this feature coming soon?  asking for a friend 😅

**Comment by jschuur** [comment]
Having it on the right also avoids the code shifting around when you pop open the file tree (at least for LTR text rendering).

Subtle, but little things like this bug me :)

**Comment by JosephTLyons** [comment]
We are working on this now!

https://zed.dev/blog/this-week-at-zed-2

**Comment by JosephTLyons** [comment]
This will be available in v0.88.0.  Closing this out now!
