### ISSUE TITLE
Protocol Buffers

### ISSUE THREAD

**Issue by imjordanxd** [zed-industries/community#411]
### Check for existing issues

- [X] Completed

### Language

Protocol Buffers

### Tree Sitter parser link

https://github.com/mitchellh/tree-sitter-proto

**Comment by JosephTLyons** [comment]
Hey @imjordanxd, this breaks convention, but I'm going to close this issue out in favor of:

- https://github.com/zed-industries/community/issues/636

Usually, we'd close the newer one if there was a duplicate (my fault), but because the newer ons has more upvotes on it, it complicates things.  Would you mind upvoting the other issue?
