### ISSUE TITLE
Evil Mode Support

### ISSUE THREAD

**Issue by anthonylei** [zed-industries/community#429]
### Check for existing issues

- [X] Completed

### Is your feature request related to a problem?

Having support of Vim key binding is great! But why just stop at Vim? Current Zed lacks the support of leader key as the main activation of commands. cmd+shift+p is great, but a single space key is much faster.

### Describe the solution you'd like

 I would love to see Zed build flexibility around key-mapping so it can support Evil mode (Vim + Emacs) in the future, such that communities can build pre-config key biddings. There are two main advantage:
- Having `space` as leader are more productive (may be a bit more opinionated). All the modern Vim & Emacs derivatives support leader key. For example, Neovim, Helix, Doom, Spacemacs all use space a leader key.
- Get the best of the both world. I can enjoy snipe/move to any text to an existing buffer while enjoying the superior key bidding of Vim.

**Comment by Kethku** [comment]
This is planned. In particular there is discussion of how to unify keybindings in a discoverable way. One proposal is to gate Zed specific bindings behind the space bar in normal mode similar to a leader key.

Your thinking is very similar to mine. Stay tuned.

**Comment by lucastrvsn** [comment]
That would be really amazing! Looking forward for that one 🙏 .

Just a suggestion, if possible: Would be great if we can navigate between editor splits using only our keyboard (even the UI elements from Zed, like file-tree). Like I do on neovim: CTRL-l goes to the right [split,window,tmux-panel], CTRL-h goes to the left [split,window,tmux-panel] and so on.

**Comment by yury** [comment]
Please consider [helix](https://helix-editor.com) key bindings.

**Comment by piazzatron** [comment]
> This is planned. In particular there is discussion of how to unify keybindings in a discoverable way. One proposal is to gate Zed specific bindings behind the space bar in normal mode similar to a leader key.
> 
> Your thinking is very similar to mine. Stay tuned.

Any updates on this? Loving Zed, having Evil support would let me fully move from VSCode :)

**Comment by idmyn** [comment]
This is possible now! Following tips from https://github.com/zed-industries/community/issues/176 I added this to my keymap.json and now I can save file with `space f s` 🙌🏻 

```
{
  "context": "Editor && vim_mode == normal && (vim_operator == none || vim_operator == n) && !VimWaiting",
  "bindings": {
    "space f s": "workspace::Save"
  }
}
```

**Comment by ConradIrwin** [comment]
I'm a little unsure what this bug is actually requesting, so sorry if I'm mis-understanding! In vim_mode, you still have access to all of zed's non-conflicting editor shortcuts (which is most of them because they were designed for non-modal editing), and as @idmyn points out, you can define your own keybindings for any zed actions.

I have also recently begun to merge zed's keybindings into vim mode's (for example `g n` lets you get at multiple cursors; which is not strictly how vim works, but much more useful). There is documentation here: https://docs.zed.dev/general/vim

* @yury Helix bindings would be really fun. Tracked here: https://github.com/zed-industries/community/issues/1777
* @lucastrvsn  key bindings for navigating between panes now exist (`ctrl-w {h,j,k,l}` in vim, `cmd-k cmd-{left, up,down,right}` in default zed). You can bind your own keyboard shortcuts to them too (see https://zed.dev/ref/default.json and search for ActivatePaneInDirection for how to do this).

Going to close this now, but please let me know (either here, or with other bug reports) if there are things that this bug was meant to encompass that I didn't understand.
