### ISSUE TITLE
Tab context menu

### ISSUE THREAD

**Issue by iamnbutler** [zed-industries/community#452]
### Check for existing issues

- [X] Completed

### Is your feature request related to a problem?

N/A

### Describe the solution you'd like

Add a context menu for tabs to enable quick access to splits, jumping to a file in the project browser, and locating the file on the operating system.

Example from Nova:
![image](https://user-images.githubusercontent.com/1714999/185182428-aa5359c1-dcb8-494e-91ac-e8a1f581d869.png)

### If applicable, add mockups / screenshots to help present your vision of the feature

N/A

**Comment by JosephTLyons** [comment]
We have the menu now.  It doesn't have everything suggested here, but maybe we can close this out and make a new fresh issue for what else to add in the menu.

**Comment by assayire** [comment]
As [**requested**](https://github.com/zed-industries/community/issues/1006#issuecomment-1456620771), adding the feature details here in this ticket.

### Describe the feature

As a Zed lover, when I right click an open tab, I would love to get a right click context menu with tab management options. Here is a short list 😜 :

- Copy File Path
- Pin Tab
- Close Other Tabs
- Close All Tabs
- Close Unmodified Tabs
- Close Tabs to the Left
- Close Tabs to the Right
- Close this tab
- Move tab to Left/Right/Top/Bottom Pane
- Move Tab to New Window

Obviously, we don't want the menu to overwhelm the user. Some work there for the design team to select the primary ones and find a way to make others available on demand.

One way I can think of is a header like strip in the menu with **_just icons_** to a few things, say `Close Other Tabs`, `Close tabs to the left`, `Close tabs to the right`, `Close Unmodified`, `Pin Tab`. Then rest of it or a subset of the rest of the items can be listed in the context menu. 

Additionally ...

- the above icon concept may be used to the context menu item in the list. For example, `Move tab to Left/Right/Top/Bottom Pane` item in the list could be `Split tab to Left/Right/Top/Bottom Pane` and icon beside it that when clicked will split and move the tab instead of split and use the same file.
- the context menu items in the list may be clicked for an action or expanded to select from more. For example, `Copy Path` could have a little 🢂 that opens to the sub-list - `Copy File Name`, `Copy Relative Path` etc. while clicking on `Copy File Path` copies the full path.

Something like that would be awesome and very useful.

**Comment by JosephTLyons** [comment]
A minimal tab context menu is coming in v0.80.2.  It currently only has tab-closing commands in it.  Im going to leave this open, as it requests more actions than just tab-closing ones.

**Comment by JosephTLyons** [comment]
Actually, let's close this one out and open new issues for adding actions to the context menu.

**Comment by vivekragunathan** [comment]
> Actually, let's close this one out and open new issues for adding actions to the context menu.

Is there an issue already or yet to be created?

**Comment by JosephTLyons** [comment]
@vivekragunathan, I haven't created one yet.  Just to show what the current iteration has, here is a screenshot:

<img width="745" alt="SCR-20230412-rmpi" src="https://user-images.githubusercontent.com/19867440/231612383-6eae1141-740b-4ca4-822e-6909a00c64dd.png">

Note, some of the names of these context menu options are a bit awkward, but they are consistent with what we already have in the command palette.  At some point, we will sweep through and update all of our awkward command and context menu option names.
