### ISSUE TITLE
External editor support with FTP clients

### ISSUE THREAD

**Issue by fuzenco** [zed-industries/community#561]
### Check for existing issues

- [X] Completed

### Is your feature request related to a problem?

The long-time macOS FTP app, Transmit, is unable to use Zed as an external editor. Double clicking a local or remote file brings Zed to the front but the file isn’t opened. I’ve tried it with both PHP and HTML files.

### Describe the solution you'd like

For the file to open in Zed editor.

**Comment by rkusa** [comment]
To help debugging, I think this might be the same as:

```bash
open -a /Applications/Zed.app lib.rs
```

Which doesn't work either and matches the described behaviour.

**Comment by rkusa** [comment]
> I ran that in Terminal and it returns file does not exist.

You probably need to replace `lib.rs` with a file path that exists on your system.

> I don’t know if you were suggesting I run it.

But no, I didn't mean to suggest to run it, sorry for not providing more context. My comment was targeted at the maintainers of Zed. Since they might not have Transmit, I wanted to provide an alternative that I think doesn't work due to the same underlying cause (and comes with macOS).

**Comment by JosephTLyons** [comment]
I'm not super familiar with this stuff, but it is possible that once this is implemented, this will work?

https://github.com/zed-industries/feedback/issues/217

**Comment by hovsater** [comment]
Is this still an issue with the latest version of Zed?

**Comment by fuzenco** [comment]
> Is this still an issue with the latest version of Zed?

Nope. Just checked. It seems to be working just fine now with my go-to client: Panic’s Transmit FTP.

Thanks for the reminder :) to check.
