### ISSUE TITLE
Replace in {buffer,project}

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/community#58]

**Comment by JosephTLyons** [comment]
Linking to https://github.com/zed-industries/zed/issues/350

**Comment by stormasm** [comment]
Looking forward to having find and replace in Zed !  thank you...

**Comment by mikayla-maki** [comment]
Can't wait!

**Comment by Aeolun** [comment]
What do the developers of Zed do instead to achieve the same result? I have a hard time imagining myself building anything like a code editor without it.

**Comment by upachler** [comment]
I find the `Command + D` solution quite cool, albeit very unusual for probably many people who are used to mainstream IDEs like myself.

My suggestion is to document this at a very prominent spot so people find it quickly. Or even put a hint about it into Zed itself.

Because once you see how it's achieved in Zed one can see it's a cool feature, at least that is my personal impression. But to get there, I looked at Zed's menus, found nothing, looked further in Command Palette, found nothing, had a look at the docs and key bindings on the web, found nothing, and then browsed github issues to find the clue for it here. Maybe other people are quicker at finding this information, but for Zed's user acceptance sake you guys should document this prominently, or even advertise it as a cool feature (because it is!);

**Comment by jansol** [comment]
Random thought but would it be possible to integrate find&replace with the LSP 'rename' function? More often than not the latter is what I *actually* want and it should have less risk of accidentally rewriting unrelated things that happen to have the same name.

**Comment by osiewicz** [comment]
Hey everyone, replace in buffer is gonna be a part of today's Preview release. :)

**Comment by osiewicz** [comment]
Replace in project is available as of latest stable (0.106.2). :)
