### ISSUE TITLE
Align One Dark theme more consistent with Atom One Dark Color Palette

### ISSUE THREAD

**Issue by reduxdj** [zed-industries/community#671]
### Check for existing issues

- [X] Completed

### Is your feature request related to a problem?

Atom has really nice syntax highlighting with its One Dark theme, I was excited about the One Dark theme, but it doesn't match what i've been used to for several years.

### Describe the solution you'd like

I'd like the theme to match, i really like the skittles rainbow of colors in Atom's One Dark theme.

### If applicable, add mockups / screenshots to help present your vision of the feature
Atom  - Rust
<img width="558" alt="Screen Shot 2022-11-07 at 7 43 37 PM" src="https://user-images.githubusercontent.com/322547/200470486-5fedb9a3-b01e-4489-8586-d6b4fc53730e.png">

Zed - Rust
<img width="635" alt="Screen Shot 2022-11-07 at 7 43 29 PM" src="https://user-images.githubusercontent.com/322547/200470508-3e9b4b12-f38e-4cf9-bdcd-39ab37fdc6a3.png">

Typescript - Atom
<img width="508" alt="Screen Shot 2022-11-07 at 7 48 38 PM" src="https://user-images.githubusercontent.com/322547/200470798-b79a5e91-9ccf-45fe-b4cf-0a5deff77314.png">

Typescript - Zed
<img width="529" alt="Screen Shot 2022-11-07 at 7 47 26 PM" src="https://user-images.githubusercontent.com/322547/200470624-331642d8-0919-405f-b888-dc1165ceac04.png">

**Comment by iamnbutler** [comment]
Hey there – We have an approach to resolve this in progress. No promises on when it lands, but this actually has to do with the way we construct themes in Zed. We've been working in the background to make our system more robust to allow themes to remap colors beyond the base mapping, but there is still a bit of work to do before this lands.

For reference, here is a few screenshots:

Old system:
![image](https://user-images.githubusercontent.com/1714999/200615844-0d177db0-2dd1-492a-a332-60c694e9793f.png)

New system:
![image](https://user-images.githubusercontent.com/1714999/200615742-6f8b7e15-f828-4bbc-b940-9434a3b9067f.png)

One Dark in Atom:
![image](https://user-images.githubusercontent.com/1714999/200623690-9b6040eb-ed1f-4583-b103-7ea5e48a939e.png)

There is still some tweaking to do one One Dark itself, as well as there will be some minor differences due to differences in the way our syntax highlighting works/highlighting definitions.

**Comment by reduxdj** [comment]
This is awesome, can't wait!

**Comment by swarnimarun** [comment]
I second others, really killed all the mood for me because the themes made it very hard to properly work, I will be looking forward to the theming fix update :)

zed Andromeda,
![rust code for perspective](https://user-images.githubusercontent.com/19930870/206931366-61e501ca-9c84-4a36-a43f-a9631539fb38.png)

zed with one dark,
![Screenshot 2022-12-12 at 3 32 03 AM](https://user-images.githubusercontent.com/19930870/206931435-ff7e8fcc-a46d-45f4-bf11-ce8243048939.png)


in vscode (one dark something?),
![Screenshot 2022-12-12 at 3 34 06 AM](https://user-images.githubusercontent.com/19930870/206931525-dd87bb2f-4dfe-4db6-96d6-d2bcc407d470.png)

I would understand if it was a tree-sitter thing but nvim seems to work fine(sorry I don't use one dark on nvim),
![Screenshot 2022-12-12 at 3 35 25 AM](https://user-images.githubusercontent.com/19930870/206931570-f1b9d6c5-e89b-447f-be9d-5e6eeaafa7f9.png)

If we can just get a bit of the separation b/w different tokens, I will definitely try giving zed daily driving a shot. Reminds me of the sublime times in a good way (pun intended).

Also opening huge files in zed works(congrats on the work for that), tried with a 10 million line file, yes you may have guessed it they were logs. Just don't ask why I need to open them in an editor. haha(vscode has issues after a few dozen thousand lines).

**Comment by iamnbutler** [comment]
Glad y'all are excited for custom theme support. We'll get to it at some point. There are a chain of projects blocking it currently.

More faithful alignment to themes should come sooner however, I have a PR open but there is a few things that need to change before it can be merged. I'd expect sometime Jan if things go well :)
