### ISSUE TITLE
Add `editor::CopyPath` similar to `project_panel::CopyPath`

### ISSUE THREAD

**Issue by javierbyte** [zed-industries/community#699]
### Check for existing issues

- [X] Completed

### Is your feature request related to a problem?

Not a problem.

### Describe the solution you'd like

I would like to be able to copy the relative path of the current selected file from the editor. Currently I can do that from the sidebar with `project_panel::CopyPath` but it seems there is no equivalente inside `editor::`

**Comment by chriskrycho** [comment]
VS Code has this feature and I use it *all* the time; I came here to report it and found the existing issue. It's particularly handy for doing things like jumping from the editor view to a terminal (built-in or otherwise) to perform an operation on a file that is better done via CLI.

Here's how it works in VS Code (and note the associated shortcut):

https://user-images.githubusercontent.com/2403023/203350812-2ee14cea-e7d1-4500-ab23-70620e8cae31.mp4

**Comment by JosephTLyons** [comment]
We now have `editor::copy path` and `editor::copy relative path`.  Closing this issue out.
