### ISSUE TITLE
[vim-mode] Enter in normal mode inserts newline

### ISSUE THREAD

**Issue by d12bb** [zed-industries/community#831]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When pressing Enter in Vim/Neovim, the cursor jumps to the beginning of the next line. In Zed, pressing Enter in normal mode actually inserts the newline as if one pressed it in insert mode.

### Environment

Zed 0.67.5 – /Applications/Zed.app
macOS 13.1
architecture arm64

**Comment by JosephTLyons** [comment]
cc @Kethku

**Comment by hotleave** [comment]
I also found that when I input `:w` in command mode, and then press  `Enter` to submit, it will also insert a new line at the cursor

**Comment by noritada** [comment]
It seems to me that 'inserting newline' issue has been fixed in the latest v0.77.3 release.
However, although Vim's `Enter` is the same as `move to next line + move to the first non-space character`, it seems to me that current `Enter` in Vim mode only does `move to next line`.
So, this issue has not yet been completely resolved.
