### ISSUE TITLE
Bash support

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/community#86]

**Comment by BuonOmo** [comment]
I had a hard time finding the issue, hence here are some keywords to help someone else searching for this issue:

- zsh language server
- shell support
- sh syntax

:heart:

**Comment by sigurpol** [comment]
Having then shellcheck as integrated linter would be the cherry on the cake but already syntax highlighting would be tremendously helpful.

**Comment by cktang88** [comment]
Agree with @sigurpol , @JosephTLyons do you have a sense of the level of effort of just syntax highlighting vs full support of language server etc.?

**Comment by iamnbutler** [comment]
Working on highlighting for this now :)

**Comment by Daeraxa** [comment]
@iamnbutler you could always try https://github.com/pulsar-edit/pulsar/blob/master/pulsar.sh which, whilst it isn't the most complicated bash script in the entire world (but still has quite a few complex bits),  does come with the added benefit that you can blame Max for some of it. It normally shows up with quite a lot of pretty colours when highlighted.

**Comment by iamnbutler** [comment]
> does come with the added benefit that you can blame Max for some of it.
Ahaha I'll be sure to do this.

**Comment by exalted** [comment]
I'd also add these to the list:

- https://iterm2.com/shell_integration/bash
- https://raw.githubusercontent.com/Homebrew/install/master/install.sh
- https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh
- https://raw.githubusercontent.com/Homebrew/brew/master/completions/bash/brew

**Comment by jbergstroem** [comment]
- https://github.com/pgrange/bash_unit/blob/master/bash_unit
- https://github.com/nvm-sh/nvm/blob/master/install.sh
- lots of scripts in here: https://github.com/ohmybash/oh-my-bash

**Comment by iamnbutler** [comment]
> I'd also add these to the list:
> 
> * https://iterm2.com/shell_integration/bash
> * https://raw.githubusercontent.com/Homebrew/install/master/install.sh
> * https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh
> * https://raw.githubusercontent.com/Homebrew/brew/master/completions/bash/brew

This first one seems to break the `tree-sitter-bash` grammar. the others seem to work fine however.

I don't _think_ it is a big enough issue to stop us from shipping it, but likely changes would need to be upstreamed to the grammar to deal with whatever error is causing highlighting to break on that particular script. I haven't taken the time to diagnose it yet.

**Comment by exalted** [comment]
@iamnbutler sure! No pushback from my side. I appreciate your work. :high-five:

**Comment by mikayla-maki** [comment]
@iamnbutler just shipped this in 0.96 🥳

**Comment by iamnbutler** [comment]
FYI there is likely a few cases the highlighting breaks, but they are pretty extreme from what I've found, and will require grammar updates to fix.

If you find a relatively simple case something breaks please let me know!

Happy to go over some of the more complex places I found where this breaks if any enterprising individual wants to contribute to improving the official tree-sitter grammar (https://github.com/tree-sitter/tree-sitter-bash)

**Comment by exalted** [comment]
🎸

**Comment by b-fuze** [comment]
@iamnbutler for one of my scripts Zed's Bash highlighting breaks for a good chunk of the file on line 835 [here](https://github.com/b-fuze/batch-encoder/blob/master/encoder.sh#L835). 

It's also be nice if it could highlight the `local` and `declare` Bash keywords as well :D

Other than that, thanks for the awesome work!

**Comment by iamnbutler** [comment]
Can you see if there are any errors in the syntax tree view?
<img width="555" alt="CleanShot 2023-07-20 at 10 45 01@2x" src="https://github.com/zed-industries/community/assets/1714999/b322133b-2dd4-41df-b3a2-956bf68007a7">

I'll get the keywords added :)

**Comment by b-fuze** [comment]
@iamnbutler Yeah, checking the syntax tree debugger there were errors at the `case` blocks in both of my examples.

## First example

The parser is unable to parse Bash's `extglob` syntax, which is documented in the Bash manual on the second section here https://www.gnu.org/software/bash/manual/bash.html#Pattern-Matching

<details>
<summary>Actual broken code & what's removed to fix the parsing</summary>
Broken parsing:
 
![image](https://github.com/zed-industries/community/assets/10504957/bc837f39-88e1-44b3-9eb7-220e2b9d7a4c)

What's removed to fix it:
![image](https://github.com/zed-industries/community/assets/10504957/66f1f7bd-bc6a-4284-bb1e-9344ff6c4051)
</details> 

<details>
<summary>Screenshot of syntax tree parsing error</summary>

![image](https://github.com/zed-industries/community/assets/10504957/21454412-e297-41c1-a615-5e4bac752cce)

</details>

## Second example
The parser is unable to parse an escaped space followed by wildcard glob in a `case` arm apparently. Maybe the escaped space is parsed incorrectly?

<details>
<summary>Actual broken code & what's removed to fix the parsing</summary>
Broken parsing:

![image](https://github.com/zed-industries/community/assets/10504957/ce8d124f-0e7f-48ac-8894-1a5895df63df)

What's removed to fix it:
![image](https://github.com/zed-industries/community/assets/10504957/f055be5c-d210-4e81-ac83-3a54233215a0)
</details>

<details>
<summary>Screenshot of syntax tree parsing error</summary>

![image](https://github.com/zed-industries/community/assets/10504957/97694a4c-0a0e-4c38-83c0-d8aea001ecae)

</details>

<hr>

And since we're on the topic of keywords, I have a list of some that I think should be added:
<details>
<summary>Screenshot of the keywords rendered</summary>

![image](https://github.com/zed-industries/community/assets/10504957/c2120b1b-eea3-491f-9db1-ded12737c9ac)

</details>

I just added examples to show how the keywords are used but really only care about the keywords themselves, even though some should probably have special parsing (like `let`'s arithmetic syntax and the ones related to manipulating variables like `typeset`/`readonly`/`local`/`declare`/`export`/`unset`—these all actually mostly share syntax, so they can likely share parsing rules) it will probably take too much time for all the special syntax stuff.

```bash
# Some keywords highlighted correctly
export foo=bar
unset foo

# Some missing/incorrectly highlighted? Bash keywords
source ~/.bashrc
. ~/.bashrc # same as `source` above
cd ~
pwd
pushd ~
popd +1
command echo -h
coproc my_coproc "sleep 1000"
let foo=10+10 # this is actually arithmetic expansion, i.e. actual arithmetic is 
              # happening. That might be too much work to properly highlight though.
declare foo=20
typeset foo=20
readonly fizz=baz
mapfile foo < myfile.txt
readarray foo < myfile.txt
read foo bar <<< "bar foo"
set -xe
shift 1
shopt -s globstar
exec new_command
exit 1
trap "echo bye" EXIT
kill -9 $$ # This is an actual Bash built-in btw, not an external command
eval "echo some_bash"
disable readonly
enable readonly
alias puts=echo
type echo
echo foo
printf foo
printf "fizz"
test true
wait %1
fg %1
bg %1
jobs
ulimit -a # This is also a Bash built-in
getopts ...
break # for loops
continue # for loops
return # only valid in a function body
```

**Comment by iamnbutler** [comment]
> @iamnbutler for one of my scripts Zed's Bash highlighting breaks for a good chunk of the file on line 835 [here](https://github.com/b-fuze/batch-encoder/blob/master/encoder.sh#L835). And another one (also for a `case` statement)—that breaks the rest of the file—in the NVM script [here](https://github.com/nvm-sh/nvm/blob/c6e35bae08ac4ea329c36aaaaf951b32a4612d80/nvm.sh#L1876).
> 
> It's also be nice if it could highlight the `local` and `declare` Bash keywords as well :D
> 
> Other than that, thanks for the awesome work!

I've shipped those two keywords, you should see it in a few days on preview/a week or so on stable!

**Comment by iamnbutler** [comment]
Awesome, thanks for the detailed examples and additional keywords.

I'll see about adding the additional keywords.

For the parsing issues, this would require upstream changes to `https://github.com/tree-sitter/tree-sitter-bash`. If you want to get your hands dirty, feel free to take a stab at those :)

Otherwise it will probably take someone more comfortable with `tree-sitter` than me to fix this. It might be worth opening an issue in that repo around it.

**Comment by b-fuze** [comment]
Thanks! For the whitespace escaping issue it seems that someone has already opened a PR fixing that tree-sitter/tree-sitter-bash#170. I do want to learn Tree-Sitter so this would be a good opportunity indeed!
